### ISSUE TITLE
G729 linking issue, libs are not generated for proper architecture 

### ISSUE THREAD

**Issue by Dpkpadhy** [saravanandm/pjsip-g729codec#1]
Hey Saravanandm,  
Thx for the sharing the code changes for integrating G729 to PJSIP. 
But i am facing few linking issue. 

i compiled for every architecture arm-v7, armv7s , arm-64, i386, x86-64, and i can see the libs got generated. But when i use lipo to make it single library file getting error as below.

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: specifed architecture type (armv7) for file (third_party/lib-armv7/libg729codec-armv7-apple-darwin_ios.a) does not match its cputype (16777223) and cpusubtype (3) (should be cputype (12) and cpusubtype (9))

i Used as below to link all the libraries :
xcrun -sdk iphoneos lipo -arch i386 pjsip/lib-iphonesim/libpjsua2-i386-apple-darwin_ios.a -arch x86_64 pjsip/lib_iphonesim64/libpjsua2-x86_64-apple-darwin_ios.a -arch armv7 pjsip/lib-armv7/libpjsua2-armv7-apple-darwin_ios.a -arch armv7s pjsip/lib-armv7s/libpjsua2-armv7s-apple-darwin_ios.a -arch arm64 pjsip/lib-arm64/libpjsua2-arm64-apple-darwin_ios.a -create -output pjsip/lib/libpjsua2-arm-apple-darwin9.a

Also when i compile the PJSIP code, also i can see the linking error's 
Looks like the even if the libs got generated its not built for proper architecture. 
Can you please let me know what i missed, or anything else i need to check, struggling from last few days, any help really appreciate.

PJSIP stack version : 2.5

**Comment by saravnandm** [comment]
Hi Dpkpadhy, 
First of all thanks for your interest. Right now i'm working on creating patches for pjsip2.5 version. Its 80% done and hope new patch will solve your problem. Also I personal felt the patches i have released for pjsip2.0 version is bit difficult and take more time to integrate. So working on that as well. You can expect the update soon.

**Comment by Dpkpadhy** [comment]
Hi Saravanandm,

Thanks for the update. yesterday i tried to integrate and succeeded with PJSIP2.5 version. 
It is building for all architecture and calls are successful with G729 codec. 

i'll update soon the extra code changes.

Thanks again, your details on integrating to PJSIP 2.1 helped a lot.

**Comment by saravnandm** [comment]
Released a patch for pjsip-2.5 https://github.com/saravanandm/pjsip2.5-g729codec
